version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678aA@
      MYSQL_DATABASE: e_learning
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1235678aA@
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    container_name: e-learning
    ports:
      - "8088:8088"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/e_learning
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1235678aA@
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  mysql_data: